{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "styx.fullname" . }}-clickhouse
  labels:
    {{- include "styx.componentLabels" (dict "root" . "component" "clickhouse") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.clickhouse.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: native
      port: {{ .Values.clickhouse.service.nativePort }}
      targetPort: native
      protocol: TCP
  selector:
    {{- include "styx.selectorLabels" (dict "root" . "component" "clickhouse") | nindent 4 }}
{{- end }}
