{{- if .Values.router.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "styx.fullname" . }}-router
  labels:
    {{- include "styx.componentLabels" (dict "root" . "component" "router") | nindent 4 }}
spec:
  type: {{ .Values.router.service.type }}
  ports:
    - name: http
      port: {{ .Values.router.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "styx.selectorLabels" (dict "root" . "component" "router") | nindent 4 }}
{{- end }}
