"""Pydantic models for Styx SDK request and response types.

These models mirror the OpenAI API types and add Styx-specific metadata.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field


# ---------------------------------------------------------------------------
# Styx metadata (extracted from custom response headers)
# ---------------------------------------------------------------------------


class StyxMetadata(BaseModel):
    """Styx-specific metadata returned alongside every response.

    This data is extracted from custom ``X-Styx-*`` response headers and
    gives visibility into routing, caching, and latency.
    """

    provider: Optional[str] = Field(
        default=None,
        description="The upstream provider that served this request (e.g. 'openai', 'anthropic').",
    )
    cache_hit: Optional[bool] = Field(
        default=None,
        description="Whether the response was served from the semantic cache.",
    )
    latency_ms: Optional[int] = Field(
        default=None,
        description="End-to-end latency in milliseconds as measured by Styx.",
    )
    complexity: Optional[str] = Field(
        default=None,
        description="The complexity classification of the request (e.g. 'simple', 'moderate', 'complex').",
    )
    request_id: Optional[str] = Field(
        default=None,
        description="Unique request identifier for debugging and support.",
    )


# ---------------------------------------------------------------------------
# Chat completion types
# ---------------------------------------------------------------------------


class FunctionCall(BaseModel):
    """A function call generated by the model."""

    name: str
    arguments: str


class ToolCall(BaseModel):
    """A tool call generated by the model."""

    id: str
    type: Literal["function"] = "function"
    function: FunctionCall


class ChatMessage(BaseModel):
    """A single message in a chat conversation."""

    role: Literal["system", "user", "assistant", "tool", "function"]
    content: Optional[str] = None
    name: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    tool_call_id: Optional[str] = None
    function_call: Optional[FunctionCall] = None


class TopLogprob(BaseModel):
    """Log probability information for a single token."""

    token: str
    logprob: float
    bytes: Optional[List[int]] = None


class TokenLogprob(BaseModel):
    """Log probability for a token with top alternatives."""

    token: str
    logprob: float
    bytes: Optional[List[int]] = None
    top_logprobs: List[TopLogprob] = Field(default_factory=list)


class ChoiceLogprobs(BaseModel):
    """Log probabilities for a completion choice."""

    content: Optional[List[TokenLogprob]] = None


class Choice(BaseModel):
    """A single completion choice."""

    index: int
    message: ChatMessage
    finish_reason: Optional[str] = None
    logprobs: Optional[ChoiceLogprobs] = None


class Usage(BaseModel):
    """Token usage statistics for a completion request."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0


class ChatCompletion(BaseModel):
    """A complete chat completion response.

    This mirrors the OpenAI ``ChatCompletion`` object and adds an
    ``styx``-namespaced ``metadata`` field.
    """

    model_config = ConfigDict(extra="allow")

    id: str
    object: Literal["chat.completion"] = "chat.completion"
    created: int
    model: str
    choices: List[Choice]
    usage: Optional[Usage] = None
    system_fingerprint: Optional[str] = None

    # Styx extension
    metadata: StyxMetadata = Field(default_factory=StyxMetadata)


# ---------------------------------------------------------------------------
# Streaming (chunked) types
# ---------------------------------------------------------------------------


class DeltaMessage(BaseModel):
    """Partial message content delivered in a streaming chunk."""

    role: Optional[str] = None
    content: Optional[str] = None
    tool_calls: Optional[List[ToolCall]] = None
    function_call: Optional[FunctionCall] = None


class StreamChoice(BaseModel):
    """A single choice inside a streaming chunk."""

    index: int
    delta: DeltaMessage
    finish_reason: Optional[str] = None
    logprobs: Optional[ChoiceLogprobs] = None


class ChatCompletionChunk(BaseModel):
    """A single server-sent event chunk during streaming.

    This mirrors the OpenAI ``ChatCompletionChunk`` object and adds
    Styx metadata.
    """

    model_config = ConfigDict(extra="allow")

    id: str
    object: Literal["chat.completion.chunk"] = "chat.completion.chunk"
    created: int
    model: str
    choices: List[StreamChoice]
    system_fingerprint: Optional[str] = None
    usage: Optional[Usage] = None

    # Styx extension
    metadata: StyxMetadata = Field(default_factory=StyxMetadata)


# ---------------------------------------------------------------------------
# Embeddings types
# ---------------------------------------------------------------------------


class Embedding(BaseModel):
    """A single embedding vector."""

    object: Literal["embedding"] = "embedding"
    index: int
    embedding: List[float]


class EmbeddingUsage(BaseModel):
    """Token usage for an embedding request."""

    prompt_tokens: int = 0
    total_tokens: int = 0


class EmbeddingResponse(BaseModel):
    """Response from an embeddings API call."""

    model_config = ConfigDict(extra="allow")

    object: Literal["list"] = "list"
    data: List[Embedding]
    model: str
    usage: EmbeddingUsage = Field(default_factory=EmbeddingUsage)

    # Styx extension
    metadata: StyxMetadata = Field(default_factory=StyxMetadata)


# ---------------------------------------------------------------------------
# Model listing types
# ---------------------------------------------------------------------------


class Model(BaseModel):
    """A single model entry."""

    id: str
    object: Literal["model"] = "model"
    created: Optional[int] = None
    owned_by: Optional[str] = None


class ModelList(BaseModel):
    """Response from the models list endpoint."""

    model_config = ConfigDict(extra="allow")

    object: Literal["list"] = "list"
    data: List[Model]


# ---------------------------------------------------------------------------
# Request helper types
# ---------------------------------------------------------------------------


class ChatCompletionRequest(BaseModel):
    """Parameters for a chat completion request.

    This is used internally for validation before sending to the API.
    """

    model_config = ConfigDict(extra="allow")

    model: str
    messages: List[Dict[str, Any]]
    temperature: Optional[float] = None
    top_p: Optional[float] = None
    n: Optional[int] = None
    stream: Optional[bool] = None
    stop: Optional[Union[str, List[str]]] = None
    max_tokens: Optional[int] = None
    presence_penalty: Optional[float] = None
    frequency_penalty: Optional[float] = None
    logit_bias: Optional[Dict[str, float]] = None
    user: Optional[str] = None
    tools: Optional[List[Dict[str, Any]]] = None
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None
    response_format: Optional[Dict[str, Any]] = None
    seed: Optional[int] = None
    logprobs: Optional[bool] = None
    top_logprobs: Optional[int] = None


class EmbeddingRequest(BaseModel):
    """Parameters for an embedding request."""

    model_config = ConfigDict(extra="allow")

    model: str
    input: Union[str, List[str]]
    encoding_format: Optional[Literal["float", "base64"]] = None
    dimensions: Optional[int] = None
    user: Optional[str] = None
